services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12357595
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  backend:
    container_name: backend_dev
    build:
      context: ./task-manager-backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3001"
    env_file:
      - ./task-manager-backend/.env
    volumes:
      - ./task-manager-backend:/app
      - /app/node_modules
    depends_on:
      - postgres

  frontend:
    container_name: frontend_dev
    build:
      context: ./task-manager-frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./task-manager-frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3000
    depends_on:
      - backend

volumes:
  postgres_dev_data:
