version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_prod
    restart: always
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12357595
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - taskmanager_network

  backend:
    container_name: backend_prod
    build:
      context: ./task-manager-backend
      dockerfile: Dockerfile
      target: production
    restart: always
    env_file:
      - ./task-manager-backend/.env.prod
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - taskmanager_network

  frontend:
    container_name: frontend_prod
    build:
      context: ./task-manager-frontend
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - taskmanager_network

volumes:
  postgres_prod_data:

networks:
  taskmanager_network:
    driver: bridge
