services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_prod
    restart: always
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12357595
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

  backend:
    container_name: backend_prod
    build:
      context: ./task-manager-backend
      dockerfile: Dockerfile
      target: production
    ports:
      - "3001:3001"
    env_file:
      - ./task-manager-backend/.env.prod
    depends_on:
      - postgres

  frontend:
    container_name: frontend_prod
    build:
      context: ./task-manager-frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - ./task-manager-frontend/.env.prod.local
    depends_on:
      - backend

volumes:
  postgres_prod_data:
