name: Fullstack CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # -----------------------
  # Backend
  # -----------------------
  backend:
    runs-on: ubuntu-latest

    # Service PostgreSQL ajoutÃ© ici
    services:
      postgres-db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12357595
          POSTGRES_DB: task_manager_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: task-manager-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install backend dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

      - name: Run integration tests (E2E)
        # Injection des variables d'environnement pour NestJS
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_USER: postgres
          DATABASE_PASSWORD: 12357595
          DATABASE_NAME: task_manager_db
          JWT_SECRET: 'topSecret51'
          NODE_ENV: test
        run: npm run test:e2e

      - name: Build backend
        run: npm run build

  # -----------------------
  # Frontend
  # -----------------------
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: task-manager-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:3001
          NEXT_PUBLIC_APP_NAME: "Task Manager App"
          NODE_ENV: production
