name: Fullstack CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # -----------------------
  # Backend
  # -----------------------
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: task-manager-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install backend dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

      - name: Run integration tests
        run: npm run test:e2e

      - name: Build backend
        run: npm run build

  # -----------------------
  # Frontend
  # -----------------------
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: task-manager-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:3001   # <- ton backend service
          NEXT_PUBLIC_APP_NAME: "Task Manager App"
          NODE_ENV: production
